# Generated by Django 3.2.25 on 2026-02-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PE_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('current_share_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('earnings_per_share', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('highest_earnings_per_share', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
            ],
        ),
    ]
