# Generated by Django 3.2.25 on 2026-02-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PERatios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pe_data',
            name='current_share_price',
            field=models.DecimalField(blank=True, decimal_places=2, default='', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pe_data',
            name='earnings_per_share',
            field=models.DecimalField(blank=True, decimal_places=2, default='', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pe_data',
            name='highest_earnings_per_share',
            field=models.DecimalField(blank=True, decimal_places=2, default='', max_digits=5, null=True),
        ),
    ]
