# Generated by Django 3.2.25 on 2026-02-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PERatios', '0002_auto_20260222_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pe_data',
            name='current_share_price',
            field=models.DecimalField(blank=True, decimal_places=2, default='', max_digits=8, null=True),
        ),
    ]
